#############################################################################
# Makefile for building: imageConverter
# Generated by qmake (3.1) (Qt 6.7.2)
# Project:  imageConverter.pro
# Template: app
# Command: /home/abderahman/Qt/6.7.2/gcc_64/bin/qmake -o Makefile imageConverter.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/opencv4 -I../../../Qt/6.7.2/gcc_64/include -I../../../Qt/6.7.2/gcc_64/include/QtWidgets -I../../../Qt/6.7.2/gcc_64/include/QtGui -I../../../Qt/6.7.2/gcc_64/include/QtCore -I. -I. -I../../../Qt/6.7.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/abderahman/Qt/6.7.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/abderahman/Qt/6.7.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/abderahman/Qt/6.7.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = imageConverter1.0.0
DISTDIR = /home/abderahman/برمجة/c++/imageConverter/.tmp/imageConverter1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/abderahman/Qt/6.7.2/gcc_64/lib -Wl,-rpath-link,/home/abderahman/Qt/6.7.2/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_videoio /home/abderahman/Qt/6.7.2/gcc_64/lib/libQt6Widgets.so /home/abderahman/Qt/6.7.2/gcc_64/lib/libQt6Gui.so /home/abderahman/Qt/6.7.2/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../../Qt/6.7.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdf.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qgstreamermediaplugin_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannelquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webviewquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/permissions.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/uic.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/lex.prf \
		imageConverter.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = imageConverter
DESTDIR       = 
TARGET        = imageConverter


first: all
####### Build rules

imageConverter: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: imageConverter.pro ../../../Qt/6.7.2/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt/6.7.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdf.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qgstreamermediaplugin_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannelquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webviewquick.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/permissions.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/uic.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/6.7.2/gcc_64/mkspecs/features/lex.prf \
		imageConverter.pro \
		../../../Qt/6.7.2/gcc_64/lib/libQt6Widgets.prl \
		../../../Qt/6.7.2/gcc_64/lib/libQt6Gui.prl \
		../../../Qt/6.7.2/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile imageConverter.pro
../../../Qt/6.7.2/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/common/unix.conf:
../../../Qt/6.7.2/gcc_64/mkspecs/common/linux.conf:
../../../Qt/6.7.2/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt/6.7.2/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt/6.7.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt/6.7.2/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt/6.7.2/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt/6.7.2/gcc_64/mkspecs/qconfig.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_chartsqml.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdf.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdf_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfquick.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfquick_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qgstreamermediaplugin_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlbuiltins.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlbuiltins_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlls_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlnetwork.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_shadertools.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_shadertools_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_spatialaudio.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannelquick.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webchannelquick_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequick.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequick_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webviewquick.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.7.2/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/toolchain.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/default_post.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/permissions.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/qt.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/resources_functions.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/resources.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/moc.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/uic.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/qmake_use.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/file_copies.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/yacc.prf:
../../../Qt/6.7.2/gcc_64/mkspecs/features/lex.prf:
imageConverter.pro:
../../../Qt/6.7.2/gcc_64/lib/libQt6Widgets.prl:
../../../Qt/6.7.2/gcc_64/lib/libQt6Gui.prl:
../../../Qt/6.7.2/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile imageConverter.pro

qmake_all: FORCE


all: Makefile imageConverter

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/6.7.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/6.7.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o moc_predefs.h ../../../Qt/6.7.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/QMainWindow \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtversionchecks.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtconfiginclude.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qassert.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtnoop.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtypes.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtversion.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qflags.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qyieldcpu.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qconstructormacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdarwinhelpers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qexceptionhandling.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qforeach.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qttypetraits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfunctionpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmalloc.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qminmax.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qoverload.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qswap.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtresource.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qttranslation.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtgui-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtguiexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobject.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstring.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qchar.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpair.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydataops.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qxptype_traits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20functional.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20memory.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringfwd.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20type_traits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlatin1stringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qanystringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringconverter.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompare.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcomparehelpers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfloat16.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmath.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiterable.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qscopeguard.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q23utility.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qaction.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qicon.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsize.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrect.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qimage.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qregion.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qline.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qset.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qhash.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfont.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qendian.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qbitmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qevent.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qurl.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qeventpoint.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qvectornd.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpointingdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qinputdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qscreen.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QList \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QObject \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QRect \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QSize \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QSizeF \
		../../../Qt/6.7.2/gcc_64/include/QtGui/QTransform \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnativeinterface.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qscreen_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreapplication_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfuture.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfutureinterface.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtsan_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qresultstore.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfuture_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qthreadpool.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qthread.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrunnable.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qexception.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpromise.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qguiapplication_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QString \
		moc_predefs.h \
		../../../Qt/6.7.2/gcc_64/libexec/moc
	/home/abderahman/Qt/6.7.2/gcc_64/libexec/moc $(DEFINES) --include /home/abderahman/برمجة/c++/imageConverter/moc_predefs.h -I/home/abderahman/Qt/6.7.2/gcc_64/mkspecs/linux-g++ -I/home/abderahman/برمجة/c++/imageConverter -I/usr/include/opencv4 -I/home/abderahman/Qt/6.7.2/gcc_64/include -I/home/abderahman/Qt/6.7.2/gcc_64/include/QtWidgets -I/home/abderahman/Qt/6.7.2/gcc_64/include/QtGui -I/home/abderahman/Qt/6.7.2/gcc_64/include/QtCore -I/usr/include/c++/14 -I/usr/include/x86_64-linux-gnu/c++/14 -I/usr/include/c++/14/backward -I/usr/lib/gcc/x86_64-linux-gnu/14/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/6.7.2/gcc_64/libexec/uic
	/home/abderahman/Qt/6.7.2/gcc_64/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/QMainWindow \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtversionchecks.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtconfiginclude.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qassert.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtnoop.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtypes.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtversion.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qflags.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qyieldcpu.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qconstructormacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdarwinhelpers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qexceptionhandling.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qforeach.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qttypetraits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfunctionpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmalloc.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qminmax.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qoverload.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qswap.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtresource.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qttranslation.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtgui-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtguiexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobject.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstring.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qchar.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpair.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydataops.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qxptype_traits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20functional.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20memory.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringfwd.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20type_traits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlatin1stringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qanystringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringconverter.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompare.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcomparehelpers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfloat16.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmath.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiterable.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qscopeguard.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q23utility.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qaction.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qicon.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsize.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrect.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qimage.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qregion.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qline.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qset.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qhash.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfont.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qendian.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qbitmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qevent.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qurl.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qeventpoint.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qvectornd.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpointingdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qinputdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qscreen.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QList \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QObject \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QRect \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QSize \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QSizeF \
		../../../Qt/6.7.2/gcc_64/include/QtGui/QTransform \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnativeinterface.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qscreen_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreapplication_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfuture.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfutureinterface.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtsan_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qresultstore.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfuture_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qthreadpool.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qthread.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrunnable.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qexception.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpromise.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qguiapplication_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QString \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/QMainWindow \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtversionchecks.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtconfiginclude.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtdeprecationmarkers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtpreprocessorsupport.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qassert.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtnoop.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtypes.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtversion.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtclasshelpermacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qflags.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qyieldcpu.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qconstructormacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdarwinhelpers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qexceptionhandling.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qforeach.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qttypetraits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfunctionpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmalloc.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qminmax.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qoverload.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qswap.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtenvironmentvariables.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtresource.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qttranslation.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtgui-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtguiexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfunctionaltools_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobject.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstring.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qchar.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpair.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qarraydataops.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qxptype_traits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20functional.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20memory.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringfwd.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q20type_traits.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlatin1stringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qanystringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringconverter.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcompare.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcomparehelpers.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfloat16.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmath.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiterable.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qscopeguard.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/q23utility.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qaction.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qicon.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsize.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrect.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qimage.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qregion.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qline.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qset.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qhash.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfont.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qendian.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qbitmap.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qevent.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qurl.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qeventpoint.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qvectornd.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qpointingdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qinputdevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qscreen.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QList \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QObject \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QRect \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QSize \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QSizeF \
		../../../Qt/6.7.2/gcc_64/include/QtGui/QTransform \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qnativeinterface.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qscreen_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcoreapplication_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfuture.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfutureinterface.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtsan_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qresultstore.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfuture_impl.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qthreadpool.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qthread.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qrunnable.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qexception.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qpromise.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/6.7.2/gcc_64/include/QtGui/qguiapplication_platform.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/QString \
		ui_mainwindow.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/QFileDialog \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qfiledialog.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdir.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfile.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qdatetime.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qcalendar.h \
		../../../Qt/6.7.2/gcc_64/include/QtCore/qtimezone.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qdialog.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/QMessageBox \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../Qt/6.7.2/gcc_64/include/QtWidgets/qdialogbuttonbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/imageConverter/bin || mkdir -p $(INSTALL_ROOT)/opt/imageConverter/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/imageConverter/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/imageConverter/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/imageConverter/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/imageConverter/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

